"""initial tables

Revision ID: 07a247087278
Revises: 
Create Date: 2026-02-13 14:26:44.968662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a247087278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_table_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('definition_code', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_table_id'], ['dataset_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_table_id', 'column_name', name='uq_dataset_column')
    )
    op.create_table('dataset_joins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('left_dataset_table_id', sa.UUID(), nullable=False),
    sa.Column('left_column', sa.String(), nullable=False),
    sa.Column('right_dataset_table_id', sa.UUID(), nullable=False),
    sa.Column('right_column', sa.String(), nullable=False),
    sa.Column('join_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['left_dataset_table_id'], ['dataset_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_dataset_table_id'], ['dataset_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_joins')
    op.drop_table('dataset_columns')
    op.drop_table('dataset_tables')
    op.drop_table('datasets')
    # ### end Alembic commands ###
